services:
  hassio:
    image: homeassistant/home-assistant
    container_name: hassio
    network_mode: "host"
    volumes:
      - type: bind
        source: custom_components/
        target: /config/custom_components
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    #      - type: bind
    #        source: /dev/ttyUSB0
    #        target: /dev/ttyUSB0
    #      - type: bind
    #        source: /dev/ttyUSB1
    #        target: /dev/ttyUSB1
    restart: "unless-stopped"